module.exports = [
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        WebSocket: "readonly",
        Blob: "readonly",
        URL: "readonly",
        // Dashboard globals
        $: "readonly",
        _state: "readonly",
        _selTicker: "readonly",
        _selTickerTime: "readonly",
        _hmFilter: "readonly",
        _tfPoints: "readonly",
        _chartZoom: "readonly",
        _zoomDragStart: "readonly",
        _lastTradingHash: "readonly",
        _lastSticks: "readonly",
        _resizeTimer: "readonly",
        _prevTrades: "readonly",
        _startTime: "readonly",
        _sigFilter: "readonly",
        _uniFilter: "readonly",
        _seenSignals: "readonly",
        _expandedCell: "readonly",
        _expandedPos: "readonly",
        _groupOpen: "readonly",
        _lastChartLen: "readonly",
        _lastChartLastMid: "readonly",
        _renderedSigKeys: "readonly",
        _renderedSigFullKeys: "readonly",
        _lastSigFilter: "readonly",
        setState: "readonly",
        setSelTicker: "readonly",
        setSelTickerTime: "readonly",
        setHmFilter: "readonly",
        setTfPoints: "readonly",
        setSigFilter: "readonly",
        setUniFilter: "readonly",
        setChartZoom: "readonly",
        setZoomDragStart: "readonly",
        setLastTradingHash: "readonly",
        setLastSticks: "readonly",
        setResizeTimer: "readonly",
        fmt$: "readonly",
        fmtS: "readonly",
        fmtPct: "readonly",
        fmtSz: "readonly",
        fmtT: "readonly",
        fmtT2: "readonly",
        fmtT4: "readonly",
        el: "readonly",
        sigClass: "readonly",
        stratBadge: "readonly",
        stClass: "readonly",
        stName: "readonly",
        stSymbol: "readonly",
        toast: "readonly",
        setupCanvas: "readonly",
        drawGrid: "readonly",
        drawPriceChart: "readonly",
        renderEquityChart: "readonly",
        initChartZoom: "readonly",
        updateZoomIndicator: "readonly",
        renderHeader: "readonly",
        renderCommand: "readonly",
        renderRisk: "readonly",
        renderStrategyPerf: "readonly",
        renderFunding: "readonly",
        renderHeatmap: "readonly",
        renderDetail: "readonly",
        renderConditions: "readonly",
        renderTrading: "readonly",
        renderPositions: "readonly",
        renderSignals: "readonly",
        renderUniverse: "readonly",
        renderJournal: "readonly",
        renderControls: "readonly",
        updateApp: "readonly",
        poll: "readonly",
        connectWS: "readonly",
        updateClock: "readonly",
        initTabs: "readonly",
        selectTicker: "readonly",
        sendCommand: "readonly",
        startRecorder: "readonly",
        stopRecorder: "readonly",
        exportCSV: "readonly"
      }
    },
    rules: {
      "no-unused-vars": ["warn", { "varsIgnorePattern": "^_" }],
      "no-undef": "error",
      "no-console": "off",
      "semi": ["error", "always"],
      "quotes": ["error", "single"]
    }
  }
];
